### PR TITLE
voltdbclient/voltserializer: no need caching variable for one time usage

### PR DESCRIPTION
**Pull request by mehmetalisavas**

### CODE REVIEW

**Comment by benjaminballard** [comment]
Hi mehmetalisavas,

Thanks for the pull request!

Could you please sign a Contributor License Agreement?  This is something we need before we can review and incorporate your contribution.  You can sign it electronically or on paper and send us the image in whatever format is easiest for you.

You can download the agreement here: https://www.voltdb.com/contributor-license-agreement/

Thanks,
Ben

**Comment by mehmetalisavas** [comment]
@benjaminballard Thanks,
Its done 👍

**Comment by benjaminballard** [comment]
Hi, did you email it to support@voltdb.com?  I haven't seen it yet.

**Comment by mehmetalisavas** [comment]
@benjaminballard actually, sent it to contribute@voltdb.org as written in agreement docs :/

**Comment by mehmetalisavas** [comment]
@benjaminballard Sent to support@voltdb.com 👍

**Pull request merged**
